### ISSUE TITLE
Move TrySmalltalk to its own repo

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber-examples#71]
As described in https://github.com/amber-smalltalk/amber-examples/issues/69 the [amber-smalltalk/amber-examples/trysmalltalk](https://github.com/amber-smalltalk/amber-examples/tree/master/trysmalltalk)  repository should be in its own repository [amber-smalltalk/trysmalltalk](https://github.com/amber-smalltalk/trysmalltalk)

**Comment by tomrake** [comment]
I am going to force push my repo

**Comment by tomrake** [comment]
This repo is directly based on @hhzl work (and others) on the trysmalltalk directory in https://github.com/amber-smalltalk/amber-examples

**Comment by hhzl** [comment]
OK

**Comment by tomrake** [comment]
By using the branch [gh-pages](https://github.com/amber-smalltalk/trysmalltalk/tree/gh-pages) you an make a previous page served by github at:

https://amber-smalltalk.github.io/trysmalltalk/

**Comment by hhzl** [comment]
Great! https://amber-smalltalk.github.io/trysmalltalk/
