### ISSUE TITLE
Snap.svg demonstration

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber-examples#75]
I'd like to add a [snap.svg] example which shows how to add and use an external library.

@amber-smalltalk/owners , may I ask you for a [code review](https://github.com/hhzl/Amber-snapsvg-demo/issues/1).

After that I'd like to move the code to the amber organisation.

**Comment by sebastianconcept** [comment]
This is really great. I didn't even heard about Snap.

Good call @hhzl !!

Thanks for doing this

**Comment by hhzl** [comment]
You are welcome, it fits well with https://trello.com/c/gbecTh6f/19-integrate-a-javascript-library

**Comment by sebastianconcept** [comment]
Exactly what I was thinking!

There is some structure layed out here:
https://docs.google.com/document/d/1YzEr460oo_OpZLvkicrCbbms0uDBVQ3RsQt3vQchcuU/edit

What about writing it @hhzl?

**Comment by hhzl** [comment]
@sebastianconcept Not a yes nor a not at this time. So if somebody wants to pick it he or she should go ahead.

**Comment by hhzl** [comment]
Version reviewed by Herby copied from

https://github.com/hhzl/Amber-snapsvg-demo

to this repo
https://github.com/amber-smalltalk/amber-examples/tree/gh-75/snap.svg

**Comment by hhzl** [comment]
Done with #77
