### ISSUE TITLE
Update snap.svg to 0.14.3

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber-examples#78]
git checkout -b gh-78
    npm install
    bower install helios --save-dev
    grunt devel
    amber serve

**Comment by hhzl** [comment]
``bower.json``  has

     "dependencies": {
        "amber": "^0.14.1",
        "snap.svg": "~0.3.0",
      },
      "devDependencies": {
        "amber-ide-starter-dialog": "^0.1.0",
        "amber-attic": "^0.1.0",
        "helios": "~0.3.4"
      }

**Comment by hhzl** [comment]
### Adding the snap.svg package in Helios

![snap svg in helios from 2015-01-26 17 08 24](https://cloud.githubusercontent.com/assets/1112023/5904159/76aaf930-a57e-11e4-8229-7a95af4fc789.png)

### Sitll Load problem
![snap svg in helios from 2015-01-26 17 08 24](https://cloud.githubusercontent.com/assets/1112023/5904142/690ff7d0-a57e-11e4-8013-19729a5a21e7.png)

**Comment by herby** [comment]
snap.svg should be a string

Hannes Hirzel wrote:

**Comment by herby** [comment]
and you probably want to import it into variable, so you don't write the require call yourself, so it should be:

imports: {'snapSvgLib' -> 'snap.svg'}

Just the good old dynamic array there, no magic. Either string to just load or an association to also put it to package-wide variable.

Hannes Hirzel wrote:

**Comment by hhzl** [comment]
imports: {'snapSvgLib' -> 'snap.svg'}

package-wide variable, what is that? How do I access it?

**Comment by herby** [comment]
You use it in any method that is part of the package.

Hannes Hirzel wrote:

**Comment by hhzl** [comment]
![helios snap svg from 2015-01-26 18 23 14](https://cloud.githubusercontent.com/assets/1112023/5905511/7725692c-a588-11e4-9318-3caae036d7f9.png)




![helios snap svg 2015-01-26 18 26 13](https://cloud.githubusercontent.com/assets/1112023/5905583/f57ff134-a588-11e4-87ff-4c8050cf1c66.png)

**Comment by herby** [comment]
Ah, that. Yes, compiler need to take those into account, which it does not yet. Fill an issue. You can proabably do the quick workaround by finding where compiler check for unknown var and just faking the test to be always successful.

**Comment by herby** [comment]
Web's 'jQuery' import worked because 'jQuery' is one of the exceptions which are allowed by default.

**Comment by herby** [comment]
(or, you can leave the require call there for the time being and only import the string, without the variable mapping, until the issue with compiler is solved (which is in fact the right way to do 0.14.3, as the compilation taking imports into account only appears in 0.14.4))

**Comment by hhzl** [comment]
@herby you mean for 0.14.3 I should use

    imports: {'snap.svg'}


in the package definition and then get access to it with

      snapLib := require value: 'snap.svg'

I.e. the current method 

     doSnapSvg

     "translation to Smalltalk points 1 to 4 of
     http://snapsvg.io/start/ "

    | s snapLib bigCircle smallCircle |
    snapLib := require value: 'snap.svg'.
    s := snapLib value: 300 value: 600.
    
    bigCircle := s circle: 150 value: 150 value: 100.
    bigCircle attr: #{'fill' -> '#bada55'. 'stroke' -> '#000'. 'strokeWidth' -> 5}.
    smallCircle := s circle: 100 value: 150 value: 70.
    "Transcript show: s outerSVG."
    "s inspect"

should work without a change?

**Comment by herby** [comment]
Yes, sadly, you cannot compile the use of the variable yet.

Hannes Hirzel wrote:

**Comment by hhzl** [comment]
Unfortunately it does not work with a string either nor does the v0.14.1 version work when upgraded to v0.14.3.

See https://github.com/hhzl/Amber-snapsvg-demo/issues/3#issuecomment-71548469

 ``bower.json`` allows for this as the **[caret ^](https://github.com/hhzl/Amber-snapsvg-demo/issues/3#issuecomment-71548469)** is used in front of the Amber version number.

**Comment by herby** [comment]
What do you mean by 'it does not work' exactly? Caret is ok, it's there exactly for that reason. 0.14.1 is compatible with 0.14.3, so it should be automatically upgraded. Please do not remove caret from anything in amber-examples repo (if something is not working, the right way is to update the caret to show new version. like `^0.14.3` so as to disallow 0.14.1, certainly not fixing it at old 0.14.1 without the caret) and then upgrading the project itself to work.

AFAICT, there is not change breaking change at all in 0.14.2->0.14.3, thing were only added (imports), nothing was changed not to work. What is the problem you have with 0.14.3?

**Comment by hhzl** [comment]
OK, I am aware of the fact that I should not remove the caret from the Amber version number in ``bower.json``. I.e. it has to stay ``"amber": "^0.14.1"`` .

I am  doing this testing in my own repo https://github.com/hhzl/Amber-snapsvg-demo

**Comment by herby** [comment]
In fact, once you use imports in the project, it should be changed to "^0.14.3" (but still wih caret). Imports are backwards compatible to use (so you can publish lib with imports), but not backwards compatible to develop (for that you need 0.14.3+ or you destroy them when committing the package).

Hannes Hirzel wrote:

**Comment by herby** [comment]
(I am still interested what may be the problem with 0.14.3, as 0.14.2 only took compatibility of and 0.14.3 brought no breaking changes)

**Comment by hhzl** [comment]
The [test](https://github.com/hhzl/Amber-snapsvg-demo/issues/3) with Amber ^0.14.1 (requested in bower.json) and 0.14.3 installed.

**Comment by hhzl** [comment]
[Retest](https://github.com/hhzl/Amber-snapsvg-demo/issues/5) with Amber ^0.14.1 (requested in bower.json) and **0.14.4** installed was successful.
